### ISSUE TITLE
Fetch current week for API call.

### ISSUE THREAD

**Issue by mweisz** [mweisz/sap-menus-backend#1]

**Comment by jonaskeutel** [comment]
What would you prefer? The next five days from now on or really the current week from Monday to Friday, regardless of what day we have? One could argue for both... I started with fetching the current week, but changing to the next five days wouldn't make much more effort, I guess.

**Comment by jonaskeutel** [comment]
Decided to go for the current week. Done with 7b791b2ad8e26a7d35279859fcd14e4763f11085
